' Program Listing 40.2
' Nuts & Volts: Stamp Applications, June 1998

' Allophone constants for "TALKER.BAS"

SYMBOL	PA1	= $00	'  10 ms pause (before BB, DD, GG and JH)
SYMBOL	PA2	= $01	'  30 ms pause (before BB, DD, GG and JH)
SYMBOL	PA3	= $02	'  50 ms pause (before PP, TT, KK and CH)
			'              (and between words)
SYMBOL	PA4	= $03	' 100 ms pause (between clauses and sentences)
SYMBOL	PA5	= $04	' 200 ms pause (between clauses and sentences)

			' sample word

SYMBOL	OY	= $05	' bOY
SYMBOL	AY	= $06	' skY
SYMBOL	EH	= $07	' End
SYMBOL	KK3	= $08	' Comb
SYMBOL	PP	= $09	' Pow
SYMBOL	JH	= $0A	' doDGe
SYMBOL	NN1	= $0B	' thiN
SYMBOL	IH	= $0C	' sIt
SYMBOL	TT2	= $0D	' To
SYMBOL	RR1	= $0E	' Rural
SYMBOL	AX	= $0F	' sUcceed

SYMBOL	MM	= $10	' Milk
SYMBOL	TT1	= $11	' parT
SYMBOL	DH1	= $12	' THey
SYMBOL	IY	= $13	' sEE
SYMBOL	EY	= $14	' bEIge
SYMBOL	DD1	= $15	' coulD
SYMBOL	UW1	= $16	' tO
SYMBOL	AO	= $17	' AUght
SYMBOL	AA	= $18	' hOt
SYMBOL	YY2	= $19	' Yes
SYMBOL	AE	= $1A	' hAt
SYMBOL	HH1	= $1B	' He
SYMBOL	BB1	= $1C	' Business
SYMBOL	TH	= $1D	' THin
SYMBOL	UH	= $1E	' bOOk
SYMBOL	UW2	= $1F	' fOOd

SYMBOL	AW	= $20	' OUt
SYMBOL	DD2	= $21	' Do
SYMBOL	GG3	= $22	' wiG
SYMBOL	VV	= $23	' Vest
SYMBOL	GG1	= $24	' Got
SYMBOL	SH	= $25	' SHip
SYMBOL	ZH	= $26	' aZure
SYMBOL	RR2	= $27	' bRain
SYMBOL	FF	= $28	' Food
SYMBOL	KK2	= $29	' sKy
SYMBOL	KK1	= $2A	' Can't
SYMBOL	ZZ	= $2B	' Zoo
SYMBOL	NG	= $2C	' aNchor
SYMBOL	LL	= $2D	' Lake
SYMBOL	WW	= $2E	' Wool
SYMBOL	XR	= $2F	' repaiR

SYMBOL	WH	= $30	' WHig
SYMBOL	YY1	= $31	' Yes
SYMBOL	CH	= $32	' CHurCH
SYMBOL	ER1	= $33	' fIR
SYMBOL	ER2	= $34	' fIR
SYMBOL	OW	= $35	' bEAU
SYMBOL	DH2	= $36	' THey
SYMBOL	SS	= $37	' veSt
SYMBOL	NN2	= $38	' No
SYMBOL	HH2	= $39	' Hoe
SYMBOL	_OR	= $3A	' stORe		(note leading underscore)
SYMBOL	AR	= $3B	' alARm
SYMBOL	YR	= $3C	' cleaR
SYMBOL	GG2	= $3D	' Guest
SYMBOL	EL	= $3E	' saddLE
SYMBOL	BB2	= $3F	' Business

' end of Allophone table
